name: CI/CD Pipeline to app on AKS

on:
  push:
    branches:
      - main
      - dev
      - staging
      - prod
  pull_request:
    branches:
      - main
      - dev
      - staging
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set environment variable
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})  # Extract branch name
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "staging" ]]; then
            echo "ENV_NAME=staging" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ env.ENV_NAME }}-${{ github.run_number }}
          docker build -t ${{ vars.ACR_NAME }}.azurecr.io/myapp:$IMAGE_TAG .

                
      - name: Check ACR Name
        run: |
         echo "ACR Name: ${{ vars.ACR_NAME }}"

      - name: Log in to Azure Container Registry
        run: |
         echo "Logging in to ACR: ${{ vars.ACR_NAME }}"
         az acr login --name ${{ vars.ACR_NAME }}
         
      - name: Tag and Push Docker Image to ACR
        run: |
          IMAGE_TAG=${{ env.ENV_NAME }}-${{ github.run_number }}
          docker tag myapp:$IMAGE_TAG ${{ vars.ACR_NAME }}.azurecr.io/myapp:$IMAGE_TAG
          docker push ${{ vars.ACR_NAME }}.azurecr.io/myapp:$IMAGE_TAG
           
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Deploy to AKS (Dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          helm upgrade --install myapp ./helm/myapp --namespace ${{ vars.NAMESPACE }} --values ./k8s/dev-values.yaml

      - name: Deploy to AKS (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          helm upgrade --install myapp ./helm/myapp --namespace ${{ vars.DEV.NAMESPACE }} --values ./k8s/staging-values.yaml

      - name: Deploy to AKS (Prod)
        if: github.ref == 'refs/heads/prod'
        run: |
          helm upgrade --install myapp ./helm/myapp --namespace ${{ vars.NAMESPACE }} --values ./k8s/prod-values.yaml
