name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - staging
      - prod
  pull_request:
    branches:
      - main
      - dev
      - staging
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure using Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set up Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.sha }} .

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Tag and Push Docker Image to ACR
        run: |
          docker tag myapp:${{ github.sha }} ${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Deploy to AKS (Dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          helm upgrade --install myapp ./helm/myapp --namespace ${{ secrets.NAMESPACE }} --values ./k8s/dev-values.yaml

      - name: Deploy to AKS (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          helm upgrade --install myapp ./helm/myapp --namespace ${{ secrets.NAMESPACE }} --values ./k8s/staging-values.yaml

      - name: Deploy to AKS (Prod)
        if: github.ref == 'refs/heads/prod'
        run: |
          helm upgrade --install myapp ./helm/myapp --namespace ${{ secrets.NAMESPACE }} --values ./k8s/prod-values.yaml
