name: CI/CD Pipeline to app on AKS    

on:
  push:
    branches:
      - main
      - dev
      - staging
      - prod
  pull_request:
    branches:
      - main
      - dev
      - staging
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set environment variable
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})  # Extract branch name
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "ENV_NAME=prod" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "staging" ]]; then
            echo "ENV_NAME=staging" >> $GITHUB_ENV
          else
            echo "ENV_NAME=dev" >> $GITHUB_ENV
          fi
          echo "IMAGE_TAG=${{ env.ENV_NAME }}-${{ github.run_number }}" >> $GITHUB_ENV
          echo "Final IMAGE_TAG: ${{ env.IMAGE_TAG }}"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Kubernetes Context
        run: |
          az aks get-credentials --resource-group ${{ vars.RESOURCE_GROUP }} --name ${{ vars.AKS_CLUSTER_NAME }} --overwrite-existing
          kubectl config current-context


      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.run_number }} .

      - name: Check ACR Name
        run: |
          echo "ACR Name: ${{ vars.ACR_NAME }}"

      - name: Log in to Azure Container Registry
        run: |
          echo "Logging in to ACR: ${{ vars.ACR_NAME }}"
          az acr login --name ${{ vars.ACR_NAME }}

      - name: Tag and Push Docker Image to ACR
        run: |
          docker tag myapp:${{ github.run_number }} ${{ vars.ACR_NAME }}.azurecr.io/myapp:${{ github.run_number }}
          docker push ${{ vars.ACR_NAME }}.azurecr.io/myapp:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Set Image Tag for Deployment
        run: |
          echo "IMAGE_TAG=${{ env.ENV_NAME }}-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Deploy to AKS
        run: |
          helm upgrade --install myapp ./helm/myapp \
            --namespace ${{ vars.NAMESPACE }} \
            --set image.repository=${{ vars.ACR_NAME }}.azurecr.io/myapp \
            --set image.tag=${{ github.run_number }} \
            --values ./k8s/prod-values.yaml
